### ISSUE TITLE
getting error in heroku, h10 error. App crashed

### ISSUE THREAD

**Issue by Nikola9933** [vernwalrahul/my-messenger-bot#5]
Im uploading app as it is in here but it's not working, app is crashing, can you tell mewhy or what should i do?

**Comment by vernwalrahul** [comment]
@Nikola9933  Can you upload the results of "heroku logs" or the error message that you are getting?

**Comment by Nikola9933** [comment]
I found a way to launch it now. I didnt put access from facebook .My bad

**Comment by vernwalrahul** [comment]
@Nikola9933  Since it has been resolved now, I am closing the issue.
