### ISSUE TITLE
Help with adding new user question predictions and bot answers

### ISSUE THREAD

**Issue by Nikola9933** [vernwalrahul/my-messenger-bot#6]
How can i expand the list of questions in predict_reply.py?

**Comment by vernwalrahul** [comment]
@Nikola9933  There is a separate file "predict_reply" for that purpose.  For now, you can just use the if-else command with string matching.

Try not to open any issue until you encounter an error while installing or deploying the app. Feel free to mail me, if you have any queries. :)
